### PR TITLE
Toast rather than crash when sharing giant traces

### LINKED ISSUE #25: Crash when sharing traces
Library version: 1.6
Android version: 6.0.1

```
Fatal Exception: java.lang.RuntimeException: Failure from system
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1547)
       at android.app.Activity.startActivityForResult(Activity.java:4283)
       at android.app.Activity.startActivityForResult(Activity.java:4230)
       at android.app.Activity.startActivity(Activity.java:4567)
       at android.app.Activity.startActivity(Activity.java:4535)
       at com.github.pedrovgs.lynx.LynxView.shareTraces(LynxView.java:185)
       at com.github.pedrovgs.lynx.presenter.LynxPresenter.onShareButtonClicked(LynxPresenter.java:120)
       at com.github.pedrovgs.lynx.LynxView$3.onClick(LynxView.java:321)
       at android.view.View.performClick(View.java:5702)
       at android.view.View$PerformClick.run(View.java:22546)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by android.os.TransactionTooLargeException: data parcel size 1541076 bytes
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:503)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3130)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1540)
       at android.app.Activity.startActivityForResult(Activity.java:4283)
       at android.app.Activity.startActivityForResult(Activity.java:4230)
       at android.app.Activity.startActivity(Activity.java:4567)
       at android.app.Activity.startActivity(Activity.java:4535)
       at com.github.pedrovgs.lynx.LynxView.shareTraces(LynxView.java:185)
       at com.github.pedrovgs.lynx.presenter.LynxPresenter.onShareButtonClicked(LynxPresenter.java:120)
       at com.github.pedrovgs.lynx.LynxView$3.onClick(LynxView.java:321)
       at android.view.View.performClick(View.java:5702)
       at android.view.View$PerformClick.run(View.java:22546)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

### PR DESCRIPTION
**Pull request by stkent**
Fixes #25.

@pedrovgs unlike #30, there are several fairly different ways this issue could be addressed. I've included one in this PR, but am more than happy to discuss and make changes if you'd prefer a different solution. (For example, we could build an automatic retry with truncated traces into the `shareTraces` method.)

### CODE REVIEW

**Comment by pedrovgs** [comment]
Hi @stkent, sorry for the late response. 

I think this implementation good but we should not show an error to the user if the trace is too long. We should measure the max trace size taking a look at the original implementation and don't try to send more traces than the one we can share depending on the OS version. What do you think? Can we update this PR implementing this change?

**Comment by stkent** [comment]
I'm not sure there's a known per-`Intent` limit available for us to read at runtime (see e.g. http://stackoverflow.com/questions/12496700/maximum-length-of-intent-putextra-method-force-close). The empirical "type-then-catch-the-exception" method is a way of working around that uncertainty. If you know something I don't, however, please point me to a reference in the docs!

**Comment by pedrovgs** [comment]
After researching this issue seems that there is a limit depending on the Android SDK being used and device close to 1 MB of bytes being sent using a ``Parcelable`` instance. 

Here you have some references:

* https://developer.android.com/reference/android/os/TransactionTooLargeException.html
* http://stackoverflow.com/questions/11451393/what-to-do-on-transactiontoolargeexception
* http://nemanjakovacevic.net/blog/english/2015/03/24/yet-another-post-on-serializable-vs-parcelable/

Based on this information, I'd catch the exception and if the limit is exceeded we should try to share just the last 100kb of traces. Even when the limit seems to be 1MB there is a blog post saying that it could be closer to 500kb so I think the last 100kb should be enough information. What do you think @stkent? Can we update this PR implementing this behavior?

**Comment by stkent** [comment]
Awesome, yes, I think that behavior should be possible! I'll try today and let you know how it goes :)

**Comment by pedrovgs** [comment]
Great! Let me know once the code is ready and I'll take a look again 😃

**Comment by stkent** [comment]
@pedrovgs let me know what you think of the updated suggestion!

File: lynx/src/main/java/com/github/pedrovgs/lynx/LynxView.java [hunk 1]
```diff
@@ -181,11 +185,26 @@ public LynxConfig getLynxConfig() {
...
+  @CheckResult @Override public boolean shareTraces(String fullTraces) {
+    try {
+      shareTracesInternal(fullTraces);
+      return true;
+    } catch (RuntimeException exception1) { // Likely cause is a TransactionTooLargeException on API levels 15+.
+      try {
+        /*
+         * Limit trace size to between 100kB and 400kB, since Unicode characters can be 1-4 bytes each.
+         */
+        String truncatedTraces = fullTraces.substring(0, Math.min(100000, fullTraces.length()));
```
Comment (pedrovgs) [inline lynx/src/main/java/com/github/pedrovgs/lynx/LynxView.java]: Using this ``substring`` call you are going to take the first part of the traces but the most relevant one is the last part of the traces content. Am I wrong?

Comment (stkent) [inline lynx/src/main/java/com/github/pedrovgs/lynx/LynxView.java]: Good catch, fixed!

**Comment by pedrovgs** [comment]
Great @stkent! Thank you so much for your time and patience 😃  I'm merging this PR and releasing a new version!

**Comment by stkent** [comment]
No problem, thanks for maintaining a great library!

**Comment by pedrovgs** [comment]
I've just released the new version!
